---
gate:
  driver: fake
  uri: dev.portailbib.com
paths:
  client: ../portail-webclient/dist
session_secret: ''
websocket:
  ping: 10
database:
  adapter: sqlite3
  encoding: utf8
  pool: 2
  timeout: 5000

i18n:
  name: "Portail"
  auth:
    google:
      name: "Google"
    twitter:
      name: "Twitter"
    yahoo:
      name: "Yahoo"
    microsoft:
      name: "Microsoft"
    facebook:
      name: "Facebook"
