---
session_secret: ''
database:
  adapter: sqlite3
  encoding: utf8
  pool: 2
  timeout: 5000

i18n:
  name: "Portail"
  auth:
    google:
      name: "Google"
      icon: ""
      css_id: google-plus
    twitter:
      name: "Twitter"
      icon: ""
    yahoo:
      name: "Yahoo"
      icon: ""
    microsoft:
      name: "Microsoft"
      icon: ""
      css_id: windows
    facebook:
      name: "Facebook"
      icon: ""